function [fitresult, xData, yData,gof, output] = DiodeEqu(V, I, text)
%CREATEFIT(V,I)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: I
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Dec-2019 14:39:18


%% Fit
[xData, yData] = prepareCurveData( V, I );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)-c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0009 0.6304 0.0176946035501658];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure();
h = plot(fitresult, xData, yData,'predfunc');hold on;
%fplot(fit_upper);hold off;
legend( h, 'I vs. V', 'Diode Equation', 'Location', 'NorthEast' );
% Label axes
xlabel V
ylabel I
title(strcat(text,' Diode Equation Fit'));
grid on

